#!/bin/bash

# Apache2
# OpenStack: openstack-infra/project-config

rm -fr .bundled_gems
mkdir .bundled_gems
export GEM_HOME=`pwd`/.bundled_gems
gem install bundler --no-rdoc --no-ri --verbose
$GEM_HOME/bin/bundle install
export BEAKER_set=localssh
export BEAKER_debug=yes
export BEAKER_color=no
$GEM_HOME/bin/bundle exec rspec spec/acceptance

